name: Create Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deps-update]

jobs:
  create-release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v6
      with:
        repository: "PCSX2/pcsx2"
        fetch-depth: 0
        submodules: false

    - name: Build Dependencies
      shell: cmd
      run: |
        start /w .github\workflows\scripts\windows\build-dependencies.bat

    - name: Create Dependencies Archive
      shell: cmd
      run: |
        "C:\Program Files\7-Zip\7z.exe" a pcsx2-windows-dependencies.7z .\deps

    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $RELEASE="latest-windows-dependencies"
        $REPO = "PCSX2/pcsx2-windows-dependencies"

        gh release delete $RELEASE --cleanup-tag --yes --repo $REPO || true

        # Workaround for https://github.com/cli/cli/issues/8458
        Write-Host "waiting for tag to be deleted"

        while ($true) {
            $result = gh api repos/$REPO/git/ref/tags/$RELEASE 2>$null

            if (-not $?) {
                break
            }

            Start-Sleep -Seconds 10
            Write-Host "still waiting..."
        }

        gh release create $RELEASE --latest --title "Latest Dependencies Build" --repo $REPO
        gh release upload $RELEASE ./pcsx2-windows-dependencies.7z --repo $REPO
